# Generated by Django 5.2 on 2025-05-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blacklist_token",
            field=models.CharField(default="", max_length=200),
        ),
    ]
