# Generated by Django 5.2 on 2025-05-10 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_user_blacklist_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstagramPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=150)),
                ("media_file", models.FileField(upload_to="instagram_media/")),
                ("caption", models.TextField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("scheduled_time", models.DateTimeField()),
                ("posted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_video", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instagram_posts",
                        to="app.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InstagramReel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=150)),
                ("media_file", models.FileField(upload_to="instagram_media/")),
                ("caption", models.TextField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("scheduled_time", models.DateTimeField()),
                ("posted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "audio_track",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instagram_reels",
                        to="app.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InstagramStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=150)),
                ("media_file", models.FileField(upload_to="instagram_media/")),
                ("caption", models.TextField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("scheduled_time", models.DateTimeField()),
                ("posted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("duration", models.PositiveIntegerField(default=5)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instagram_stories",
                        to="app.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
