# Generated by Django 5.2 on 2025-05-10 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_instagrampost_instagramreel_instagramstory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instagramreel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="instagramstory",
            name="user",
        ),
        migrations.DeleteModel(
            name="InstagramPost",
        ),
        migrations.DeleteModel(
            name="InstagramReel",
        ),
        migrations.DeleteModel(
            name="InstagramStory",
        ),
    ]
